CFILES = main.c

# Device
LIB_TARGET = stm32/f4
DEVICE = STM32F412CGUx

# Makefiles
OPENCM3_DIR = ../common/libopencm3
include $(OPENCM3_DIR)/mk/genlink-config.mk
include ../common/rules.mk
include $(OPENCM3_DIR)/mk/genlink-rules.mk