# Source files to compile
CPPSRC = main.cpp

#
# Define the environment
#

# ChibiOS lib directory
CHIBIOS = ../common/ChibiOS

# Directory with board.[ch] files
BOARD_DIR = ../common/board

# HAL driver folder root 
# (should have an "Inc" directory inside of it)
HAL_DRIVER = ../common/STM32L0xx_HAL_Driver

# Path to CMSIS directory 
# (should contain "Device" & "Include" directories)
CMSIS = ../common/CMSIS

# Conf directory. 
#(should contain halconf.h, mcuconf.h, chconf.h & stm32l0xx_hal_conf)
CONFDIR = ../common/conf

#
# Build rules
#
include ../common/Makefile