# Source files to compile
CPPSRC = main.cpp

# Set paths
SHARED_DIR = $(realpath ../shared/)

# ChibiOS lib directory
CHIBIOS = ../shared/ChibiOS

# Directory with board.[ch] files
BOARD_DIR = ../shared/board

# HAL driver folder root (should have an Inc directory inside of it)
HAL_DRIVER = ../shared/STM32L0xx_HAL_Driver

# Path to CMSIS directory (should contain "Device" & "Include" directories)
CMSIS = ../shared/CMSIS

# Path to directory which contains halconf.h, mcuconf.h, chconf.h & stm32l0xx_hal_conf
CONFDIR = ../shared/conf

ALLINC += ../shared

# Build rules
include ../shared/Makefile