CFILES = main.c \
        ../common/thunderpack.c

# Device
LIB_TARGET = stm32/f4
DEVICE = STM32F411CE

# Makefiles
COMMON_DIR = ../common
OPENCM3_DIR = ${COMMON_DIR}/libopencm3
include ../common/rules.mk
