# Source files to compile
CPPSRC = main.cpp

###############################################################################
# Define the environment
#

# ChibiOS lib directory
CHIBIOS = ../common/ChibiOS

# Directory with board.[ch] files
BOARD_DIR = ../common/board

# Drivers directory, from STM32CubMX
# (should contain "CMSIS" & "STM32L0xx_HAL_Driver" directories)
CUBEMX_DRIVERS = ../common/drivers

# Conf directory.
# should contain halconf.h, mcuconf.h, chconf.h
CONFDIR = ../common/conf

##############################################################################

include ../common/Makefile